from typing import Protocol, List, Optional
from app.domain.models import Book
from app.domain.extended_models import Library, Institution, CorporateClub, CommunityGroup, Marketplace


class BookRepositoryProtocol(Protocol):
    async def add(self, book: Book) -> None: ...
    async def get_by_id(self, id: str) -> Book: ...
    async def list_all(self) -> List[Book]: ...
    async def remove(self, id: str) -> None: ...
    async def update(self, id: str, book: Book) -> None: ...


class LibraryRepositoryProtocol(Protocol):
    async def add(self, library: Library) -> None: ...
    async def get_by_id(self, id: str) -> Optional[Library]: ...
    async def get_by_user_id(self, user_id: str) -> List[Library]: ...
    async def remove(self, id: str) -> None: ...
    async def update(self, id: str, library: Library) -> None: ...

# Alias for backward compatibility
LibraryRepository = LibraryRepositoryProtocol


class InstitutionRepositoryProtocol(Protocol):
    async def add(self, institution: Institution) -> None: ...
    async def get_by_id(self, id: str) -> Optional[Institution]: ...
    async def list_all(self) -> List[Institution]: ...
    async def remove(self, id: str) -> None: ...
    async def update(self, id: str, institution: Institution) -> None: ...

# Alias for backward compatibility
InstitutionRepository = InstitutionRepositoryProtocol


class CorporateClubRepositoryProtocol(Protocol):
    async def add(self, club: CorporateClub) -> None: ...
    async def get_by_id(self, id: str) -> Optional[CorporateClub]: ...
    async def list_all(self) -> List[CorporateClub]: ...
    async def remove(self, id: str) -> None: ...
    async def update(self, id: str, club: CorporateClub) -> None: ...

# Alias for backward compatibility
CorporateClubRepository = CorporateClubRepositoryProtocol


class CommunityGroupRepositoryProtocol(Protocol):
    async def add(self, group: CommunityGroup) -> None: ...
    async def get_by_id(self, id: str) -> Optional[CommunityGroup]: ...
    async def list_all(self) -> List[CommunityGroup]: ...
    async def remove(self, id: str) -> None: ...
    async def update(self, id: str, group: CommunityGroup) -> None: ...

# Alias for backward compatibility
CommunityGroupRepository = CommunityGroupRepositoryProtocol


class MarketplaceRepositoryProtocol(Protocol):
    async def add(self, item: Marketplace) -> None: ...
    async def get_by_id(self, id: str) -> Optional[Marketplace]: ...
    async def list_all_available(self) -> List[Marketplace]: ...
    async def get_by_seller_id(self, seller_id: str) -> List[Marketplace]: ...
    async def remove(self, id: str) -> None: ...
    async def update(self, id: str, item: Marketplace) -> None: ...

# Alias for backward compatibility
MarketplaceRepository = MarketplaceRepositoryProtocol
