from typing import Protocol, List
from app.domain.models import Book

class BookRepositoryProtocol(Protocol):
    async def add(self, book: Book) -> None: ...
    async def get_by_id(self, id: str) -> Book: ...
    async def list_all(self) -> List[Book]: ...
    async def remove(self, id: str) -> None: ...
    async def update(self, id: str, book: Book) -> None: ...