"""Add Library, Institution, CorporateClub, CommunityGroup, Marketplace tables

Revision ID: b8f3d7c2a1e0
Revises: 1444fd36a23e
Create Date: 2026-04-10 16:43:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b8f3d7c2a1e0'
down_revision = '1444fd36a23e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_group',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_group_creator_user_id'), 'community_group', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_community_group_id'), 'community_group', ['id'], unique=False)
    op.create_index(op.f('ix_community_group_name'), 'community_group', ['name'], unique=False)
    
    op.create_table('corporate_club',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_club_admin_user_id'), 'corporate_club', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_corporate_club_id'), 'corporate_club', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_club_name'), 'corporate_club', ['name'], unique=False)
    
    op.create_table('institution',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_id'), 'institution', ['id'], unique=False)
    op.create_index(op.f('ix_institution_name'), 'institution', ['name'], unique=False)
    
    op.create_table('library',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_book_id'), 'library', ['book_id'], unique=False)
    op.create_index(op.f('ix_library_id'), 'library', ['id'], unique=False)
    op.create_index(op.f('ix_library_user_id'), 'library', ['user_id'], unique=False)
    op.create_index('idx_library_user_book', 'library', ['user_id', 'book_id'], unique=True)
    
    op.create_table('marketplace',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('buyer_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_book_id'), 'marketplace', ['book_id'], unique=False)
    op.create_index(op.f('ix_marketplace_buyer_user_id'), 'marketplace', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_marketplace_id'), 'marketplace', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_seller_user_id'), 'marketplace', ['seller_user_id'], unique=False)
    op.create_index('idx_marketplace_available', 'marketplace', ['is_available', 'listed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_marketplace_available', table_name='marketplace')
    op.drop_index(op.f('ix_marketplace_seller_user_id'), table_name='marketplace')
    op.drop_index(op.f('ix_marketplace_id'), table_name='marketplace')
    op.drop_index(op.f('ix_marketplace_buyer_user_id'), table_name='marketplace')
    op.drop_index(op.f('ix_marketplace_book_id'), table_name='marketplace')
    op.drop_table('marketplace')
    
    op.drop_index('idx_library_user_book', table_name='library')
    op.drop_index(op.f('ix_library_user_id'), table_name='library')
    op.drop_index(op.f('ix_library_id'), table_name='library')
    op.drop_index(op.f('ix_library_book_id'), table_name='library')
    op.drop_table('library')
    
    op.drop_index(op.f('ix_institution_name'), table_name='institution')
    op.drop_index(op.f('ix_institution_id'), table_name='institution')
    op.drop_table('institution')
    
    op.drop_index(op.f('ix_corporate_club_name'), table_name='corporate_club')
    op.drop_index(op.f('ix_corporate_club_id'), table_name='corporate_club')
    op.drop_index(op.f('ix_corporate_club_admin_user_id'), table_name='corporate_club')
    op.drop_table('corporate_club')
    
    op.drop_index(op.f('ix_community_group_name'), table_name='community_group')
    op.drop_index(op.f('ix_community_group_id'), table_name='community_group')
    op.drop_index(op.f('ix_community_group_creator_user_id'), table_name='community_group')
    op.drop_table('community_group')
    # ### end Alembic commands ###